### ISSUE TITLE
Enabling "Close keyboard when using clock" option makes the time picker unresponsive to touch (Android 5.1.1)

### ISSUE THREAD

**Issue by a-pav** [felixwiemuth/SimpleReminder#49] opened 2024-04-07 16:48 UTC
Enabling "Close keyboard when using clock" option works only partially. 
That is, after enabling this option, when the time picker is touched, keyboard gets closed, but then the time picker has also became unresponsive to touch (unable to change time by finger movements.)

I couldn't find a way to change the time while the option is enabled. It seems that merely enabling the option causes this issue since I tried closing the keyboard by pressing the system's back button (and not by touching the time picker) but still the time picker wasn't responding to my touch after the keyboard was closed.

Please add the following information:
- App version: 0.9.13
- Android version: 5.1.1

<sub>Initially mentioned in #48.</sub>

**Comment by felixwiemuth** [comment] 2024-04-12 06:47
Thanks for the report and additional information. I guess it has something to do with your system not responing as expected to the request of closing the keyboard (e.g. by blocking), which is triggered when touching the time picker (regardless of whether you have already closed the keyboard or not).

It doesn't happen on some physical devices and some emulated devices which I tested with.

If you are interested or want to figure it our yourself, here is the code which is executed on touch: https://github.com/felixwiemuth/SimpleReminder/blob/f498e1fcedab155145526ece5d27bdbb8502655c/app/src/main/java/felixwiemuth/simplereminder/ui/ReminderDialogActivity.kt#L16

You could see whether it helps only triggering the action once instead of on every touch. But to include that in the solution would be a bit more complicated, as you want it to work several times in a row of course. A "cooldown" based on timestamp coule be a simple solution for that.
However, I would rather only build it in if it turns out to be a general problem.

**Comment by marzecm93** [comment] 2024-08-15 05:53
Hi!

Could You please also consider adding an option in settings to not show the keyboard automatically?
I have to close it every time I enter the reminder time because I prefer picking it on the clock. When I touch the clock, the keyboard closes and the clock moves to the middle of the screen. This "jumping clock" causes me to pick wrong hour sometimes and makes it harder to use.

Zenfone 7 Pro
Android 12
App 0.9.14

Overall, it is a great FOSS app. Does the job!

**Comment by felixwiemuth** [comment] 2024-08-24 05:32
I reproduced the issue (unresponsive time picker) in an emulator for Android 5.0 and 5.1. These are the only Android versions where this happens, so I removed the feature for these versions.

@marzecm93 This is the current behaviour. You are welcome to make a feature request as a separate issue. Please also include some arguments why you think this can be a  preferred workflow (as opposed to entering the text first, for instance).

**Closed** 2024-08-24 05:33 UTC
Labels: Bug report

**Comment by a-pav** [comment] 2024-08-24 13:50
> Please also include some arguments why you think this can be a preferred workflow (as opposed to entering the text first, for instance).

Not the person you were replying to, but for some reason, whenever I want to set a reminder for something, the name of the thing is always secondary to the time I want to be reminded of it, so I always begin by setting the time then enter a label for it. But since I've disabled the option that this issue was about, I can use the clock, even the portion that is hidden by the keyboard (through circular gesture) without needing to close the keyboard first. But I also think that having an option to disable automatic keyboard opening would be nice.
